okta:
  oauth2:
    client-id: 0oaurqe85sprMMhsh4x6
    client-secret: KHYINUdOYiORzIKXvPdmUcX1J2Pc8cX87xgncjSl
    redirect-uri: /authorization-code/callback
    issuer: https://dev-515856.okta.com/oauth2/default